2018-09-13T08:12:36.5101025-07:00 0HLGPHDB9296K:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:64416/api/values   (ca22a1cb)
2018-09-13T08:12:36.5101132-07:00 0HLGPHDB9296J:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:64416/  0 (ca22a1cb)
2018-09-13T08:12:36.6046441-07:00 0HLGPHDB9296J:00000001 [INF] Request finished in 159.1992ms 200  (791a596a)
2018-09-13T08:12:36.8360146-07:00 0HLGPHDB9296K:00000001 [INF] Request finished in 411.5106ms 404  (791a596a)
2018-09-13T08:12:39.4780468-07:00 0HLGPHDB9296J:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:64416/Logging/LogEvent/ACES application/json 206 (ca22a1cb)
2018-09-13T08:12:41.7024733-07:00 0HLGPHDB9296J:00000002 [INF] Executing action method "Logging.Controllers.LoggingController.LogEventACES (Logging)" with arguments (["Models.Requests.LogData"]) - ModelState is Valid (ba7f4ac2)
2018-09-13T08:12:45.3110366-07:00 0HLGPHDB9296J:00000002 [INF] Executed action "Logging.Controllers.LoggingController.LogEventACES (Logging)" in 5705.5848ms (afa2e885)
2018-09-13T08:12:45.4136722-07:00 0HLGPHDB9296J:00000002 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.ArgumentNullException: Value cannot be null.
Parameter name: logger
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at Logging.Controllers.LoggingController.<LogEventACES>d__6.MoveNext() in C:\Data\Developement\Logging\Logging\Logging\Controllers\LoggingController.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-09-13T08:12:45.5318448-07:00 0HLGPHDB9296J:00000002 [INF] Request finished in 6033.641ms 500 text/html; charset=utf-8 (791a596a)
